### ISSUE TITLE
Countdown is incorrect and showing negative numbers on subsequent submits

### ISSUE THREAD

**Issue by jvetyska** [balinterdi/ember-cancelable-button#2]
On your demo page, you can clearly see the issue. You click first time, it's nice 5, 4, 3 ...
On Second or any further clicks, it will still show these numbers, but also interlace in negative numbers, like -5, -6, -7 ...

It would also make sense to have a more realistic example, where the button stays in disabled mode after timed submit.

**Comment by balinterdi** [comment]
I tried to reproduce this on the demo site but couldn't:
https://cl.ly/2X3J0f350d1H

Is it possible you checked this with an older version (or an older version of the demo site)?

I fixed an issue that could have caused this [with this commit](https://github.com/balinterdi/ember-cancelable-button/commit/376ae2b6b9dc73009dbdd9d634a28df344cd5e32)

**Comment by buschtoens** [comment]
I can reproduce this with the latest deployed demo site. The demo site I get is the one that is currently pushed to `gh-pages` (aabc05a9d19b740b1d7d27cdade61534bc67b471).

**Comment by balinterdi** [comment]
Can you create a screen share to show what I do differently from you guys?

**Comment by buschtoens** [comment]
Sure. I don't think I'm doing anything different though.

https://www.youtube.com/watch?v=7XBJ_LzfFoA

**Comment by balinterdi** [comment]
@buschtoens Thanks a bunch.

Seems like I forgot to push to the gh-pages branch last time after having fixed this bug. I did now, could you check it's working fine on your end, too?

**Comment by buschtoens** [comment]
Works as expected! :)

btw since you wrote a blog post about hosting a demo site on GH pages, you might be interested in automating that. You can either do this with `ember-cli-release` ([example](https://github.com/offirgolan/ember-light-table/blob/3a6192d84f28061a7d06c27bbb7f5c0db7d2bc1b/config/release.js#L12)) or even use Travis to automate that for every tagged version. :smile:

**Comment by balinterdi** [comment]
@buschtoens Great idea :), I'm going to set it up, thank you.
